import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.166.1/build/three.module.js';
import {TEAMS,TRACKS,POINTS,createDrivers} from './config.js';
import {AudioEngine} from './audio.js';
const C=(v,a,b)=>Math.max(a,Math.min(b,v)),R=(a,b)=>a+Math.random()*(b-a),M=(n,m)=>((n%m)+m)%m;
const cd=(a,b)=>M(a-b+.5,1)-.5;
const fmt=s=>`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}.${String(Math.floor((s%1)*1000)).padStart(3,'0')}`;
function carMesh(team,scale=1){
 const g=new THREE.Group(),p=new THREE.MeshStandardMaterial({color:team.primary,metalness:.35,roughness:.35}),s=new THREE.MeshStandardMaterial({color:team.secondary,metalness:.2,roughness:.45}),k=new THREE.MeshStandardMaterial({color:0x080a0d,roughness:.8}),glass=new THREE.MeshStandardMaterial({color:0x071525,metalness:.1,roughness:.12});
 const add=(geo,mat,x,y,z)=>{const m=new THREE.Mesh(geo,mat);m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;g.add(m);return m};
 add(new THREE.BoxGeometry(1.6,.45,4),p,0,.55,0);add(new THREE.BoxGeometry(.65,.28,2.1),p,0,.47,-2.55);add(new THREE.BoxGeometry(.85,.4,1.1),glass,0,.9,-.1);add(new THREE.BoxGeometry(2.65,.12,.5),s,0,.32,-3.35);add(new THREE.BoxGeometry(2.35,.16,.5),s,0,1.0,1.75);add(new THREE.BoxGeometry(1.85,.22,.5),k,0,.34,2.0);
 const wg=new THREE.CylinderGeometry(.46,.46,.42,14);[[-1.17,-2.05],[1.17,-2.05],[-1.17,1.3],[1.17,1.3]].forEach(([x,z])=>{const w=add(wg,k,x,.46,z);w.rotation.z=Math.PI/2});
 const fm=new THREE.MeshBasicMaterial({color:0x57bfff,transparent:true,opacity:.9});[-.43,.43].forEach(x=>{const f=add(new THREE.ConeGeometry(.17,1.2,8),fm,x,.45,2.7);f.rotation.x=Math.PI/2;f.visible=false;(g.userData.flames??=[]).push(f)});
 g.scale.setScalar(scale);return g;
}
function roadGeo(curve,w,n=700){const pos=[],uv=[],idx=[],up=new THREE.Vector3(0,1,0);for(let i=0;i<=n;i++){const t=i/n,p=curve.getPointAt(t),tan=curve.getTangentAt(t).normalize(),nor=new THREE.Vector3().crossVectors(up,tan).normalize(),a=p.clone().addScaledVector(nor,-w/2),b=p.clone().addScaledVector(nor,w/2);pos.push(a.x,a.y,a.z,b.x,b.y,b.z);uv.push(0,t*80,1,t*80);if(i<n){const q=i*2;idx.push(q,q+2,q+1,q+2,q+3,q+1)}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setIndex(idx);g.computeVertexNormals();return g}
export class FormulaRushGame{
 constructor(canvas,cb={}){this.canvas=canvas;this.cb=cb;this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(1.5,devicePixelRatio||1));this.renderer.shadowMap.enabled=true;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.08;this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(62,1,.1,900);this.audio=new AudioEngine();this.keys={left:0,right:0,brake:0,nitro:0};this.drivers=createDrivers();this.team=TEAMS[1];this.trackIndex=0;this.championship=this.drivers.map(driver=>({driver,points:0}));this.qualifying={};this.finalGrid=[];this.running=false;this.paused=true;this.last=0;this.trackGroup=new THREE.Group();this.dynamic=new THREE.Group();this.scene.add(this.trackGroup,this.dynamic);this.lights();this.resize();this.loadTrack(0);requestAnimationFrame(t=>this.loop(t))}
 lights(){this.scene.add(new THREE.HemisphereLight(0xcbe4ff,0x25421c,1.7));const d=new THREE.DirectionalLight(0xffffff,2.4);d.position.set(-50,100,30);d.castShadow=true;d.shadow.mapSize.set(1024,1024);this.scene.add(d)}
 resize(){const w=innerWidth,h=innerHeight;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix()}
 selectTeam(id){this.team=TEAMS.find(t=>t.id===id)||TEAMS[0]}
 resetChampionship(){this.championship.forEach(x=>x.points=0);this.trackIndex=0;this.qualifying={};this.finalGrid=[];this.loadTrack(0)}
 beginChampionship(){this.resetChampionship();this.prepareSession('Q1')}
 loadTrack(i){this.trackIndex=i;this.track=TRACKS[i];this.trackGroup.clear();this.dynamic.clear();this.curve=new THREE.CatmullRomCurve3(this.track.points,true,'catmullrom',.08);this.length=this.curve.getLength();this.scene.background=new THREE.Color(this.track.sky);this.scene.fog=new THREE.Fog(this.track.fog,150,430);
  const grass=new THREE.Mesh(new THREE.PlaneGeometry(900,900),new THREE.MeshStandardMaterial({color:0x3a7c35,roughness:1}));grass.rotation.x=-Math.PI/2;grass.position.y=-.12;grass.receiveShadow=true;this.trackGroup.add(grass);
  const road=new THREE.Mesh(roadGeo(this.curve,this.track.roadWidth),new THREE.MeshStandardMaterial({color:0x262b33,roughness:.92,metalness:.02}));road.receiveShadow=true;this.trackGroup.add(road);
  for(const side of [-1,1]){const kerb=new THREE.Mesh(roadGeo(this.curve,1.05,700),new THREE.MeshStandardMaterial({color:side<0?0xff3448:0xf4f4f4,roughness:.8}));kerb.position.y=.035;kerb.userData.side=side;this.trackGroup.add(kerb);kerb.geometry.translate(side*(this.track.roadWidth/2+.55),0,0)}
  const treeMat=new THREE.MeshStandardMaterial({color:0x185226,roughness:1}),trunkMat=new THREE.MeshStandardMaterial({color:0x53341e});for(let i2=0;i2<120;i2++){const t=i2/120,p=this.curve.getPointAt(t),tan=this.curve.getTangentAt(t),nor=new THREE.Vector3().crossVectors(new THREE.Vector3(0,1,0),tan).normalize(),side=i2%2?1:-1,off=this.track.roadWidth/2+R(14,44),root=new THREE.Group();root.position.copy(p).addScaledVector(nor,side*off);const tr=new THREE.Mesh(new THREE.CylinderGeometry(.4,.65,4,6),trunkMat),top=new THREE.Mesh(new THREE.ConeGeometry(R(2.5,4.5),R(7,12),7),treeMat);tr.position.y=2;top.position.y=7;root.add(tr,top);this.trackGroup.add(root)}
  this.createProps();this.trackLength=this.length;this.player={driver:this.drivers.find(d=>d.team.id===this.team.id),mesh:carMesh(this.team,1),progress:0,distance:0,lateral:0,latV:0,speed:0,nitro:100,lap:1,lapTime:0,totalTime:0,position:22,jumpY:0,jumpV:0,knockdowns:0};this.dynamic.add(this.player.mesh);this.ai=[];this.pickups=[];this.ramps=[];this.placePickups();this.placeRamps();this.updateObjects();this.camera.position.set(0,5,10)}
 createProps(){const mat=new THREE.MeshStandardMaterial({color:0x151922,metalness:.35,roughness:.5}),red=new THREE.MeshStandardMaterial({color:0xff243e,emissive:0x5f0012});for(let i=0;i<8;i++){const t=M(.03+i/8,1),p=this.curve.getPointAt(t),tan=this.curve.getTangentAt(t),nor=new THREE.Vector3().crossVectors(new THREE.Vector3(0,1,0),tan).normalize(),g=new THREE.Group();g.position.copy(p).addScaledVector(nor,(i%2?1:-1)*(this.track.roadWidth/2+11));const stand=new THREE.Mesh(new THREE.BoxGeometry(18,5,8),mat);stand.position.y=2.5;g.add(stand);for(let j=0;j<12;j++){const dot=new THREE.Mesh(new THREE.BoxGeometry(.7,.7,.25),j%3===0?red:new THREE.MeshStandardMaterial({color:0xe6ecf5}));dot.position.set(-7+(j%6)*2.7,3.4+Math.floor(j/6)*-1.5,-4.15);g.add(dot)}this.trackGroup.add(g)}}
 placePickups(){const mat=new THREE.MeshStandardMaterial({color:0x25bfff,emissive:0x156eff,emissiveIntensity:2,metalness:.2,roughness:.15});for(let i=0;i<12;i++){const m=new THREE.Group(),ring=new THREE.Mesh(new THREE.TorusGeometry(.65,.16,8,20),mat);ring.rotation.x=Math.PI/2;m.add(ring);m.userData={p:M(.08+i/12,1),lane:(i%3-1)*2.4,collected:false};this.dynamic.add(m);this.pickups.push(m)}}
 placeRamps(){const mat=new THREE.MeshStandardMaterial({color:0xffa51c,metalness:.2,roughness:.55});[.24,.61,.83].forEach((p,i)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(6,1.2,9),mat);m.rotation.x=-.13;m.userData={p,lane:i%2?2.2:-2.2};this.dynamic.add(m);this.ramps.push(m)})}
 prepareSession(s){this.session=s;this.running=false;this.paused=true;this.countdown=0;this.cb.onBriefing?.({kicker:`GP ${this.trackIndex+1}/3 • ${this.track.country}`,title:`${s} • ${this.track.name}`,text:s==='RACE'?'Tre giri, 22 auto, nitro e rampe. Vai al limite senza trasformare la monoposto in arredamento.':`${s}: giro lanciato. Il format 2026 elimina 6 auto in Q1 e 6 in Q2.`,objectives:s==='Q1'?['Entra nei primi 16','Raccogli nitro','Evita i muri']:s==='Q2'?['Entra nei primi 10','Frena nelle curve lente','Usa il boost sui rettilinei']:s==='Q3'?['Attacca la pole','Massimizza ogni uscita','Niente errori']:['Tre giri','Sorpassa con il nitro','Punti ai primi 10']})}
 startDriving(){this.resetPlayer();this.buildAI();this.running=true;this.paused=false;this.countdown=3.7;this.cb.onDriveStart?.();this.audio.start()}
 resetPlayer(){Object.assign(this.player,{progress:0,distance:0,lateral:0,latV:0,speed:0,nitro:100,lap:1,lapTime:0,totalTime:0,position:22,jumpY:0,jumpV:0,knockdowns:0});this.resetPickups()}
 buildAI(){this.ai.forEach(c=>this.dynamic.remove(c.mesh));this.ai=[];const pool=this.session==='Q1'?this.drivers:this.session==='Q2'?(this.qualifying.Q1||[]).slice(0,16).map(x=>x.driver):this.session==='Q3'?(this.qualifying.Q2||[]).slice(0,10).map(x=>x.driver):(this.finalGrid.length?this.finalGrid.map(x=>x.driver):this.drivers);const others=pool.filter(d=>d.id!==this.player.driver.id);this.qualPool=pool;if(this.session==='RACE'){others.forEach((d,i)=>{const c={driver:d,mesh:carMesh(d.team,.92),distance:(i+1)*5,progress:0,lateral:(i%2?2.2:-2.2),lane:(i%2?2.2:-2.2),speed:57+d.skill*18+R(-3,3),spin:0,position:i+2,totalTime:0};this.dynamic.add(c.mesh);this.ai.push(c)})}else{this.aiTimes=others.map(d=>({driver:d,time:this.track.par/(d.skill*d.team.performance*this.track.grip)+R(-.55,.55)}))}}
 setInput(k,v){this.keys[k]=v?1:0}
 update(dt){if(!this.player)return;if(this.countdown>0){this.countdown-=dt;this.cb.onCountdown?.(this.countdown);this.updateObjects();return}if(!this.running||this.paused){this.updateObjects();return}const p=this.player,curve=this.curve,seg=curve.getTangentAt(p.progress),turn=Math.abs(seg.x)+Math.abs(seg.z);let a=27;if(this.keys.brake)a=-63;if(this.keys.nitro&&p.nitro>0&&p.speed>25){a+=50;p.nitro=C(p.nitro-31*dt,0,100);this.nitroActive=true}else{p.nitro=C(p.nitro+5*dt,0,100);this.nitroActive=false}const max=108+(this.nitroActive?31:0);p.speed=C(p.speed+a*dt,16,max);p.speed*=Math.pow(Math.abs(p.lateral)>this.track.roadWidth/2-1?.965:.998,dt*60);const steer=(this.keys.left-this.keys.right)*-1;p.latV+=steer*(12+p.speed*.03)*dt;p.latV*=Math.pow(.12,dt);p.lateral+=p.latV*dt;p.lateral=C(p.lateral,-this.track.roadWidth*.72,this.track.roadWidth*.72);p.distance+=p.speed*dt;p.progress=M(p.distance/this.trackLength,1);p.lapTime+=dt;p.totalTime+=dt;if(p.jumpY>0||p.jumpV>0){p.jumpV-=19*dt;p.jumpY+=p.jumpV*dt;if(p.jumpY<0){p.jumpY=0;p.jumpV=0}}this.checkRamps();this.checkPickups();if(this.session==='RACE'){this.updateAI(dt);this.collisions();this.positions();if(p.distance>=this.track.laps*this.trackLength)this.finishRace()}else if(p.distance>=this.trackLength)this.finishQuali();this.updateObjects();this.audio.update(p.speed/max,this.nitroActive);this.cb.onHUD?.(this.getHUD())}
 updateAI(dt){this.ai.forEach((c,i)=>{if(c.spin>0){c.spin-=dt;c.speed*=.985;c.mesh.rotation.y+=dt*9}else{c.speed=C(c.speed+R(-2,2)*dt,46,103);c.lane+=(Math.sin(performance.now()*.00035+i)*2.6-c.lane)*dt*.35}c.distance+=c.speed*dt;c.progress=M(c.distance/this.trackLength,1);c.totalTime+=dt})}
 checkRamps(){this.ramps.forEach(r=>{const d=Math.abs(cd(this.player.progress,r.userData.p))*this.trackLength;if(d<4&&Math.abs(this.player.lateral-r.userData.lane)<3&&this.player.jumpY<.1){this.player.jumpV=8.5;this.player.speed=Math.max(this.player.speed,75);this.setMsg('SALTO!',1)}})}
 checkPickups(){this.pickups.forEach(o=>{o.rotation.y+=.03;const d=Math.abs(cd(this.player.progress,o.userData.p))*this.trackLength;if(!o.userData.collected&&d<3.2&&Math.abs(this.player.lateral-o.userData.lane)<2.2){o.userData.collected=true;o.visible=false;this.player.nitro=C(this.player.nitro+38,0,100);this.audio.pickup();this.setMsg('NITRO +38%',1)}})}
 resetPickups(){this.pickups.forEach(o=>{o.userData.collected=false;o.visible=true})}
 collisions(){this.ai.forEach(c=>{if(c.spin>0)return;const d=Math.abs(this.player.distance-c.distance),l=Math.abs(this.player.lateral-c.lateral);if(d<3.5&&l<1.8&&this.player.jumpY<.7){if(this.nitroActive&&this.player.speed>72){c.spin=2.1;c.lane+=this.player.lateral<c.lateral?3:-3;this.player.knockdowns++;this.audio.impact(.8);this.setMsg('KNOCKDOWN!',1.2)}else{this.player.speed*=.61;c.speed*=.8;this.player.latV+=(this.player.lateral<c.lateral?-1:1)*2;this.audio.impact(1);navigator.vibrate?.(40);this.cb.onImpact?.();this.setMsg('CONTATTO!',.9)}}})}
 positions(){const all=[{id:this.player.driver.id,d:this.player.distance,player:true},...this.ai.map(c=>({id:c.driver.id,d:c.distance}))].sort((a,b)=>b.d-a.d);this.player.position=all.findIndex(x=>x.player)+1}
 finishQuali(){this.running=false;this.paused=true;const raw=this.player.lapTime,ideal=this.trackLength/74,time=this.track.par*(raw/ideal)/(this.team.performance*this.player.driver.skill*this.track.grip)+R(-.15,.15),res=[...this.aiTimes,{driver:this.player.driver,time}].sort((a,b)=>a.time-b.time);this.qualifying[this.session]=res;const pos=res.findIndex(x=>x.driver.id===this.player.driver.id)+1,cut=this.session==='Q1'?16:10,adv=this.session==='Q3'||pos<=cut;if(this.session==='Q1'&&!adv)this.finalGrid=this.compose(null,null,res);else if(this.session==='Q2'&&!adv)this.finalGrid=this.compose(null,res,this.qualifying.Q1);else if(this.session==='Q3')this.finalGrid=this.compose(res,this.qualifying.Q2,this.qualifying.Q1);this.cb.onSessionResult?.({type:'QUALIFYING',session:this.session,position:pos,time,advanced:adv,results:res,next:()=>{if(this.session==='Q1'&&adv)this.prepareSession('Q2');else if(this.session==='Q2'&&adv)this.prepareSession('Q3');else this.prepareSession('RACE')}})}
 compose(q3,q2,q1){q1=q1||this.qualifying.Q1||this.drivers.map(d=>({driver:d,time:99}));q2=q2||this.qualifying.Q2||q1.slice(0,16);q3=q3||this.qualifying.Q3||q2.slice(0,10);const top=q3.slice(0,10),mid=q2.filter(x=>!top.some(y=>y.driver.id===x.driver.id)).slice(0,6),ids=new Set([...top,...mid].map(x=>x.driver.id)),last=q1.filter(x=>!ids.has(x.driver.id)).slice(0,6);return[...top,...mid,...last]}
 finishRace(){this.running=false;this.paused=true;const stand=[{driver:this.player.driver,distance:this.player.distance,time:this.player.totalTime,player:true},...this.ai.map(c=>({driver:c.driver,distance:c.distance,time:c.totalTime}))].sort((a,b)=>b.distance-a.distance),pos=stand.findIndex(x=>x.player)+1;stand.forEach((x,i)=>{const e=this.championship.find(c=>c.driver.id===x.driver.id);if(e)e.points+=POINTS[i]||0});const last=this.trackIndex===TRACKS.length-1;this.cb.onSessionResult?.({type:'RACE',session:'RACE',position:pos,time:this.player.totalTime,standings:stand,knockdowns:this.player.knockdowns,lastTrack:last,next:()=>{if(last)this.cb.onChampionshipEnd?.([...this.championship].sort((a,b)=>b.points-a.points));else{this.loadTrack(this.trackIndex+1);this.qualifying={};this.finalGrid=[];this.prepareSession('Q1')}}})}
 setMsg(s,t=1){this.message=s;this.messageTimer=t}
 updateObjects(){if(!this.curve||!this.player)return;const place=(obj,p,l=0,y=0)=>{const pt=this.curve.getPointAt(M(p,1)),tan=this.curve.getTangentAt(M(p,1)).normalize(),nor=new THREE.Vector3().crossVectors(new THREE.Vector3(0,1,0),tan).normalize();obj.position.copy(pt).addScaledVector(nor,l);obj.position.y+=y;obj.rotation.y=Math.atan2(tan.x,tan.z)};place(this.player.mesh,this.player.progress,this.player.lateral,this.player.jumpY);this.player.mesh.userData.flames?.forEach(f=>{f.visible=this.nitroActive;f.scale.y=.7+Math.random()*.7});this.ai.forEach(c=>place(c.mesh,c.progress,c.lateral,.03));this.pickups.forEach(o=>place(o,o.userData.p,o.userData.lane,1.2));this.ramps.forEach(o=>place(o,o.userData.p,o.userData.lane,.55));this.cameraUpdate();if(this.messageTimer>0)this.messageTimer-=1/60}
 cameraUpdate(){const p=this.player.progress,pt=this.curve.getPointAt(p),tan=this.curve.getTangentAt(p).normalize(),nor=new THREE.Vector3().crossVectors(new THREE.Vector3(0,1,0),tan).normalize(),desired=pt.clone().addScaledVector(nor,this.player.lateral*.7).addScaledVector(tan,-10.5);desired.y=4.5+this.player.jumpY*.4;this.camera.position.lerp(desired,.12);const look=pt.clone().addScaledVector(tan,14).addScaledVector(nor,this.player.lateral*.45);look.y=1.1+this.player.jumpY*.2;this.camera.lookAt(look);this.camera.fov+=(62+(this.player.speed/108)*13+(this.nitroActive?7:0)-this.camera.fov)*.08;this.camera.updateProjectionMatrix()}
 getHUD(){if(this.messageTimer<=0)this.message=this.session==='RACE'?`P${this.player.position} • ${this.player.knockdowns} KNOCKDOWN`:`${this.session} • ${fmt(this.player.lapTime)}`;return{session:this.session,track:this.track.name,position:this.player.position,totalCars:this.session==='RACE'?22:(this.qualPool?.length||22),lap:this.session==='RACE'?Math.min(this.track.laps,Math.floor(this.player.distance/this.trackLength)+1):1,laps:this.session==='RACE'?this.track.laps:1,speed:Math.round(this.player.speed*3.6),nitro:Math.round(this.player.nitro),message:this.message||'PRONTO',progress:M(this.player.progress,1),nitroActive:this.nitroActive}}
 getMiniMapData(n=90){return Array.from({length:n},(_,i)=>this.curve.getPointAt(i/n))}
 loop(t){const dt=Math.min(.033,this.last?(t-this.last)/1000:.016);this.last=t;this.update(dt);this.renderer.render(this.scene,this.camera);requestAnimationFrame(x=>this.loop(x))}
}